services:
  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: catalog_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - gateway-network

  # Сервис для сборки productService
  productServiceBuild:
    image: openjdk:23-slim
    container_name: product_service_build
    volumes:
      - ./productService:/app
    working_dir: /app
    command: bash -c "mkdir /app/target && apt-get update && apt-get install -y maven && mvn clean package"
    depends_on:
      - postgres
    networks:
      - gateway-network

  # Сервис для сборки orderService
  orderServiceBuild:
    image: openjdk:23-slim
    container_name: order_service_build
    volumes:
      - ./orderService:/app
    working_dir: /app
    command: bash -c "apt-get update && apt-get install -y maven && mvn clean package"
    depends_on:
      - postgres
    networks:
      - gateway-network

  # Сервис для сборки apiGateway
  apiGatewayBuild:
    image: openjdk:23-slim
    container_name: api_gateway_build
    volumes:
      - ./apiGateway:/app
    working_dir: /app
    command: bash -c "apt-get update && apt-get install -y maven && mvn clean package"
    depends_on:
      - postgres
    networks:
      - gateway-network

  productService:
    image: openjdk:23-jdk-slim
    container_name: product-service
    volumes:
      - ./productService/:/app/
    command: ["sh", "-c", "until [ -f /app/target/productService-0.0.1-SNAPSHOT.jar ]; do echo 'Waiting for productService-0.0.1-SNAPSHOT.jar'; sleep 10; done; java -jar /app/target/productService-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/catalog_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8081:8081"
    depends_on:
      - postgres
      - productServiceBuild
    networks:
      - gateway-network

  orderService:
    image: openjdk:23-jdk-slim
    container_name: order-service
    volumes:
      - ./orderService/:/app/
    command: ["sh", "-c", "until [ -f /app/target/orderService-0.0.1-SNAPSHOT.jar ]; do echo 'Waiting for orderService-0.0.1-SNAPSHOT.jar'; sleep 10; done; java -jar /app/target/orderService-0.0.1-SNAPSHOT.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres_db:5432/catalog_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    ports:
      - "8082:8082"
    depends_on:
      - postgres
      - orderServiceBuild
    networks:
      - gateway-network

  apiGateway:
    image: openjdk:23-jdk-slim
    container_name: api-gateway
    volumes:
      - ./apiGateway/:/app/
    command: ["sh", "-c", "until [ -f /app/target/apiGateway-0.0.1-SNAPSHOT.jar ]; do echo 'Waiting for apiGateway-0.0.1-SNAPSHOT.jar'; sleep 10; done; java -jar /app/target/apiGateway-0.0.1-SNAPSHOT.jar"]
    ports:
      - "8090:8090"
    depends_on:
      - productService
      - orderService
      - apiGatewayBuild
    networks:
      - gateway-network

volumes:
  postgres_data:

networks:
  gateway-network:
    driver: bridge
