server:
  port: 8090

spring:
  application:
    name: apiGateway

  cloud:
    gateway:
      routes:
        - id: product-service
#          uri: http://product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**

        - id: order-service
#          uri: http://order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    urls:
      - name: Product Service
#        url: http://product-service/v3/api-docs
        url: http://localhost:8081/v3/api-docs
      - name: Order Service
#        url: http://order-service/v3/api-docs
        url: http://localhost:8082/v3/api-docs