server:
  port: 8090

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      routes:
        - id: product-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/products/**

        - id: order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/orders/**
